# Generated by Django 3.1.1 on 2020-09-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=100)),
                ('startDT', models.DateTimeField()),
                ('endDT', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('createDT', models.DateTimeField()),
                ('authors', models.ManyToManyField(to='galleryIs.Author')),
                ('genres', models.ManyToManyField(to='galleryIs.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('template', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitorsQTY', models.IntegerField()),
                ('descriprion', models.TextField(max_length=2500)),
                ('createDT', models.DateTimeField()),
                ('exhibition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='galleryIs.exhibition')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='galleryIs.template')),
            ],
        ),
        migrations.CreateModel(
            name='Refurbishment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('startDT', models.DateTimeField()),
                ('endDT', models.DateTimeField()),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryIs.painting')),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='paintings',
            field=models.ManyToManyField(to='galleryIs.Painting'),
        ),
    ]
