# Generated by Django 3.1.1 on 2020-09-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.TextField(max_length=111111111111),
        ),
    ]
